INTEREST_MAP = {

# ---------------- POLITICS ----------------
"politics": "politics",
"PoliticalHumor": "politics",
"The_Donald": "politics",
"Conservative": "politics",
"Libertarian": "politics",
"neoliberal": "politics",
"socialism": "politics",
"PoliticalDiscussion": "politics",
"Political_Revolution": "politics",
"ENLIGHTENEDCENTRISM": "politics",
"LateStageCapitalism": "politics",
"WayOfTheBern": "politics",
"SandersForPresident": "politics",
"worldpolitics": "politics",
"geopolitics": "politics",
"CanadaPolitics": "politics",
"ukpolitics": "politics",
"MHOC": "politics",
'JordanPeterson': 'politics',
    'samharris': 'politics',
    'CapitalismVSocialism': 'politics',
    'VoteBlue': 'politics',
    'ChapoTrapHouse': 'politics',
    'JoeRogan': 'politics',
    'conspiracy': 'politics',
    'BlueMidterm2018': 'politics',
    'Beto2020': 'politics',
    'AskTrumpSupporters': 'politics',
    'metacanada': 'politics',
    'COMPLETEANARCHY': 'politics',
    'stupidpol': 'politics',
    'Economics': 'politics',

# ---------------- TECHNOLOGY ----------------
"technology": "technology",
"programming": "technology",
"learnprogramming": "technology",
"webdev": "technology",
"datascience": "technology",
"Python": "technology",
"sysadmin": "technology",
"linux": "technology",
"apple": "technology",
"Android": "technology",
"GooglePixel": "technology",
"iphone": "technology",
"Amd": "technology",
"nvidia": "technology",
"reactjs": "technology",
"techsupport": "technology",
'ProgrammerHumor': 'technology',
    'excel': 'technology',
    'CryptoCurrency': 'technology',
    'ethtrader': 'technology',
    'weedstocks': 'technology',
    'dataisbeautiful': 'technology',

# ---------------- GAMING ----------------
"gaming": "gaming",
"pcmasterrace": "gaming",
"leagueoflegends": "gaming",
"Overwatch": "gaming",
"NintendoSwitch": "gaming",
"PS4": "gaming",
"Steam": "gaming",
"Minecraft": "gaming",
"FortNiteBR": "gaming",
"apexlegends": "gaming",
"GlobalOffensive": "gaming",
"RocketLeague": "gaming",
"hearthstone": "gaming",
"Pokemon": "gaming",
"StardewValley": "gaming",
"skyrim": "gaming",
"witcher": "gaming",
'ffxiv': 'gaming',
    'wow': 'gaming',
    'xboxone': 'gaming',
    'Games': 'gaming',
    'pathofexile': 'gaming',
    'MonsterHunterWorld': 'gaming',
    'starcraft': 'gaming',
    'deadbydaylight': 'gaming',
    'CODZombies': 'gaming',
    'ClashRoyale': 'gaming',
    'gtaonline': 'gaming',
    'oculus': 'gaming',
    'StarWarsBattlefront': 'gaming',
    'FortniteCompetitive': 'gaming',
    'mopeio': 'gaming',

# ---------------- SPORTS ----------------
"soccer": "sports",
"nba": "sports",
"nfl": "sports",
"sports": "sports",
"tennis": "sports",
"hockey": "sports",
"baseball": "sports",
"MMA": "sports",
"Boxing": "sports",
"bodybuilding": "sports",
"Fitness": "sports",
"formula1": "sports",
'CFB': 'sports',
    'MLS': 'sports',
    'CollegeBasketball': 'sports',
    'NYYankees': 'sports',
    'reddevils': 'sports',
    'Mariners': 'sports',
    'Gunners': 'sports',
    'fantasybaseball': 'sports',
    'Cricket': 'sports',
    'bjj': 'sports',
    'fantasyfootball': 'sports',
    'Colts': 'sports',
    'SportingKC': 'sports',
    'ripcity': 'sports',
    'FantasyMLS': 'sports',

# ---------------- MENTAL HEALTH ----------------
"depression": "mental_health",
"Anxiety": "mental_health",
"socialanxiety": "mental_health",
"mentalhealth": "mental_health",
"SuicideWatch": "mental_health",
"CPTSD": "mental_health",
"OCD": "mental_health",
"bipolar": "mental_health",
"ADHD": "mental_health",
"aspergers": "mental_health",
"schizophrenia": "mental_health",
"lonely": "mental_health",
'benzodiazepines': 'mental_health',
    'NEET': 'mental_health',
    'researchchemicals': 'mental_health',
    'Drugs': 'mental_health',
    'MultipleSclerosis': 'mental_health',
    'BPDlovedones': 'mental_health',

# ---------------- RELATIONSHIPS ----------------
"relationships": "relationships",
"relationship_advice": "relationships",
"dating": "relationships",
"dating_advice": "relationships",
"Tinder": "relationships",
"OkCupid": "relationships",
"DeadBedrooms": "relationships",
"BreakUps": "relationships",

# ---------------- PERSONALITY / IDENTITY ----------------
"mbti": "personality_identity",
"INTP": "personality_identity",
"infj": "personality_identity",
"infp": "personality_identity",
"entp": "personality_identity",
"intj": "personality_identity",
"enfj": "personality_identity",
"istp": "personality_identity",
"isfj": "personality_identity",
"ESTJ": "personality_identity",
"Enneagram": "personality_identity",
"Jung": "personality_identity",
"JungianTypology": "personality_identity",
"introvert": "personality_identity",
'ENFP': 'personality_identity',
    'entj': 'personality_identity',
    'Schizoid': 'personality_identity',
    'sociopath': 'personality_identity',
    'psychology': 'personality_identity',
    'Aphantasia': 'personality_identity',
    'slatestarcodex': 'personality_identity',

# ---------------- FINANCE / CAREER ----------------
"personalfinance": "finance_career",
"investing": "finance_career",
"wallstreetbets": "finance_career",
"financialindependence": "finance_career",
"jobs": "finance_career",
"Entrepreneur": "finance_career",
"business": "finance_career",
"cscareerquestions": "finance_career",
"povertyfinance": "finance_career",
'RealEstate': 'finance_career',
    'uberdrivers': 'finance_career',
    'InstacartShoppers': 'finance_career',

# ---------------- EDUCATION / SCIENCE ----------------
"science": "education_science",
"askscience": "education_science",
"Physics": "education_science",
"biology": "education_science",
"chemistry": "education_science",
"math": "education_science",
"statistics": "education_science",
"EngineeringStudents": "education_science",
"college": "education_science",
"ApplyingToCollege": "education_science",
'todayilearned': 'education_science',
    'Fantasy': 'education_science',
    'Futurology': 'education_science',
    'books': 'education_science',
    'IAmA': 'education_science',

# ---------------- ENTERTAINMENT ----------------
"movies": "entertainment",
"television": "entertainment",
"Music": "entertainment",
"anime": "entertainment",
"NetflixBestOf": "entertainment",
"Marvel": "entertainment",
"StarWars": "entertainment",
"gameofthrones": "entertainment",
"harrypotter": "entertainment",
"southpark": "entertainment",
'RWBY': 'entertainment',
    'Animemes': 'entertainment',
    'danganronpa': 'entertainment',
    'manga': 'entertainment',
    'ShingekiNoKyojin': 'entertainment',
    'stevenuniverse': 'entertainment',
    'freefolk': 'entertainment',
    'titanfolk': 'entertainment',
    'SevenKingdoms': 'entertainment',
    'grandorder': 'entertainment',
'IMDbFilmGeneral': 'entertainment',
    'thebachelor': 'entertainment',
    'thewalkingdead': 'entertainment',
    'startrek': 'entertainment',
    'lucifer': 'entertainment',
    'Supernatural': 'entertainment',
    'AmericanHorrorStory': 'entertainment',
    'marvelstudios': 'entertainment',
    'Documentaries': 'entertainment',
'popheads': 'entertainment',
    'hiphopheads': 'entertainment',
    'TaylorSwift': 'entertainment',
    'radiohead': 'entertainment',
    'musictheory': 'entertainment',
    'popheadscirclejerk': 'entertainment',

# ---------------- HUMOR / MEMES ----------------
"funny": "memes_humor",
"dankmemes": "memes_humor",
"memes": "memes_humor",
"AdviceAnimals": "memes_humor",
"MemeEconomy": "memes_humor",
"wholesomememes": "memes_humor",
"me_irl": "memes_humor",
"ComedyCemetery": "memes_humor",
"DeepFriedMemes": "memes_humor",
"surrealmemes": "memes_humor",
'starterpacks': 'memes_humor',
    'Showerthoughts': 'memes_humor',
    'BlackPeopleTwitter': 'memes_humor',
    'pics': 'memes_humor',
    'videos': 'memes_humor',
    'AskOuija': 'memes_humor',
    'aww': 'memes_humor',
    'gifs': 'memes_humor',
    'mildlyinteresting': 'memes_humor',
    'TheMonkeysPaw': 'memes_humor',
    'WhitePeopleTwitter': 'memes_humor',
    'trashy': 'memes_humor',
    'PublicFreakout': 'memes_humor',
    'RoastMe': 'memes_humor',
    'ChoosingBeggars': 'memes_humor',
    'insanepeoplefacebook': 'memes_humor',
    'Jokes': 'memes_humor',
    'MurderedByWords': 'memes_humor',
    'oddlysatisfying': 'memes_humor',
    'WTF': 'memes_humor',
    'interestingasfuck': 'memes_humor',
    'nottheonion': 'memes_humor',
    'OldSchoolCool': 'memes_humor',
    'iamverysmart': 'memes_humor',
    '2meirl4meirl': 'memes_humor',
    'anime_irl': 'memes_humor',
    'tifu': 'memes_humor',

# ---------------- LIFESTYLE / HEALTH ----------------
"loseit": "lifestyle_health",
"keto": "lifestyle_health",
"vegan": "lifestyle_health",
"nutrition": "lifestyle_health",
"intermittentfasting": "lifestyle_health",
"Meditation": "lifestyle_health",
"SkincareAddiction": "lifestyle_health",
"MakeupAddiction": "lifestyle_health",
'LifeProTips': 'lifestyle_health',
    'childfree': 'lifestyle_health',
    'Nootropics': 'lifestyle_health',
    'fatlogic': 'lifestyle_health',

# ---------------- CREATIVE / HOBBIES ----------------
"Art": "creative_hobbies",
"WritingPrompts": "creative_hobbies",
"writing": "creative_hobbies",
"photography": "creative_hobbies",
"Guitar": "creative_hobbies",
"woodworking": "creative_hobbies",
"3Dprinting": "creative_hobbies",
"worldbuilding": "creative_hobbies",
'criticalrole': 'creative_hobbies',
    'Pathfinder_RPG': 'creative_hobbies',
    'DnD': 'creative_hobbies',

# ---------------- SOCIAL DISCUSSION ----------------
"AskReddit": "social_discussion",
"CasualConversation": "social_discussion",
"NoStupidQuestions": "social_discussion",
"TooAfraidToAsk": "social_discussion",
"changemyview": "social_discussion",
"TrueOffMyChest": "social_discussion",
"offmychest": "social_discussion",
"Advice": "social_discussion",
'GenderCritical': 'social_discussion',
    'FeMRADebates': 'social_discussion',
    'KotakuInAction': 'social_discussion',
    'TumblrInAction': 'social_discussion',
    'CringeAnarchy': 'social_discussion',
    'enoughpetersonspam': 'social_discussion',

# ---------------- NEWS / WORLD ----------------
"worldnews": "news_world",
"news": "news_world",
"europe": "news_world",
"canada": "news_world",
"australia": "news_world",
"unitedkingdom": "news_world",

# ---------------- RELIGION / IDEOLOGY ----------------
"Christianity": "ideology_religion",
"Catholicism": "ideology_religion",
"DebateReligion": "ideology_religion",
"atheism": "ideology_religion",
"islam": "ideology_religion",
"Buddhism": "ideology_religion",
"Stoicism": "ideology_religion",
'TrueChristian': 'ideology_religion',
    'Izlam': 'ideology_religion',

# ---------------- ADULT / DATING ----------------
"sex": "relationships",
"seduction": "relationships",
"TheRedPill": "relationships",
"MGTOW": "relationships",
"PurplePillDebate": "relationships",
"NoFap": "relationships",
'datingoverthirty': 'relationships',
    'AskMen': 'relationships',
    'AskWomen': 'relationships',
    'AmItheAsshole': 'relationships',
    'sexover30': 'relationships',
    'niceguys': 'relationships',
    'askwomenadvice': 'relationships',
    'BDSMcommunity': 'relationships',
    'confession': 'relationships',

# GEOGRAPHY / LOCAL
    'Nepal': 'geography_local',
    'de': 'geography_local',
    'AskAnAmerican': 'geography_local',
    'thenetherlands': 'geography_local',
    'melbourne': 'geography_local',
    'brasil': 'geography_local',
    'ireland': 'geography_local',
    'italy': 'geography_local',
    'saskatchewan': 'geography_local',
    'Philippines': 'geography_local',

# GENERAL REDDIT
'unpopularopinion': 'general_reddit',
    'teenagers': 'general_reddit',
    'OzoneOfftopic': 'general_reddit',
    'MHOLVote': 'general_reddit',
    'MHOCMP': 'general_reddit',
    'ik_ihe': 'general_reddit',
    'MHolyrood': 'general_reddit',
    'Wishlist': 'general_reddit',
    'MHOCHolyrood': 'general_reddit',
    'bestoflegaladvice': 'general_reddit',
    'tipofmytongue': 'general_reddit',
    'tumblr': 'general_reddit',
    'Random_Acts_Of_Amazon': 'general_reddit',
    'Roadcam': 'general_reddit',
    'Sexsells': 'general_reddit',
    'shittyama': 'general_reddit',
    'TalesFromThePizzaGuy': 'general_reddit',
    'navyseals': 'general_reddit',
    'short': 'general_reddit',

# GAMING
    'magicTCG': 'gaming',
    'FireEmblemHeroes': 'gaming',
    'MMORPG': 'gaming',
    'pcgaming': 'gaming',
    'MonsterHunter': 'gaming',
    'Warframe': 'gaming',
    'Gameboy': 'gaming',
    'DevilMayCry': 'gaming',
    'smashbros': 'gaming',
    'DotA2': 'gaming',
    'silenthill': 'gaming',
    'tf2': 'gaming',
    'DarkSouls2': 'gaming',
    'Smite': 'gaming',
    'PUBATTLEGROUNDS': 'gaming',
    'Guildwars2': 'gaming',
    'Rainbow6': 'gaming',
    'dndnext': 'gaming',
    'pokemon': 'gaming',
    'gamingsuggestions': 'gaming',
    'CrusaderKings': 'gaming',
    'custommagic': 'gaming',
    'RPGdesign': 'gaming',
    'gwent': 'gaming',
    'RimWorld': 'gaming',
    'Pokemongiveaway': 'gaming',
    'MagicArena': 'gaming',
    'TwoBestFriendsPlay': 'gaming',
    'NoMansSkyTheGame': 'gaming',
    'fo4': 'gaming',
    'EliteDangerous': 'gaming',
    'thesims': 'gaming',
    'CastleClash': 'gaming',
    'WorldOfWarships': 'gaming',
    'Fallout': 'gaming',
    'fo76': 'gaming',
    '40kLore': 'gaming',
    'reddeadredemption': 'gaming',
    'SpidermanPS4': 'gaming',
    'neopets': 'gaming',
    'FIFA': 'gaming',

    # SPORTS
    'SquaredCircle': 'sports',
    'Nationals': 'sports',
    'Flyers': 'sports',
    'DynastyFF': 'sports',
    'LiverpoolFC': 'sports',
    'collegebaseball': 'sports',
    'OrlandoMagic': 'sports',

    # ENTERTAINMENT
    'rupaulsdragrace': 'entertainment',
    'asoiaf': 'entertainment',
    'TheWeeknd': 'entertainment',
    'deathgrips': 'entertainment',
    'YMS': 'entertainment',
    'Kanye': 'entertainment',
    'MoviePassClub': 'entertainment',
    'ContraPoints': 'entertainment',
    'BoJackHorseman': 'entertainment',
    'bigbangtheory': 'entertainment',
    'Ice_Poseidon': 'entertainment',

    # MEMES / HUMOR
    'milliondollarextreme': 'memes_humor',
    'whowouldwin': 'memes_humor',
    'justneckbeardthings': 'memes_humor',
    'circlebroke2': 'memes_humor',
    'PrequelMemes': 'memes_humor',
    'greentext': 'memes_humor',
    'Drama': 'memes_humor',
    '4chan': 'memes_humor',
    'BikiniBottomTwitter': 'memes_humor',
    'mildlyinfuriating': 'memes_humor',
    'iamatotalpieceofshit': 'memes_humor',
    'Whatcouldgowrong': 'memes_humor',
    'HistoryMemes': 'memes_humor',
    'SubredditDrama': 'memes_humor',
    'im14andthisisdeep': 'memes_humor',
    'gatekeeping': 'memes_humor',
    'Unexpected': 'memes_humor',
    'Damnthatsinteresting': 'memes_humor',
    'assholedesign': 'memes_humor',
    'thanosdidnothingwrong': 'memes_humor',
    'CrappyDesign': 'memes_humor',
    'Cringetopia': 'memes_humor',
    'facepalm': 'memes_humor',
    'BeAmazed': 'memes_humor',
    'PewdiepieSubmissions': 'memes_humor',
    'WatchPeopleDieInside': 'memes_humor',
    'MadeMeSmile': 'memes_humor',

    # TECHNOLOGY
    'buildapc': 'technology',
    'MachineLearning': 'technology',
    'vba': 'technology',

    # FINANCE / CAREER
    'antiMLM': 'finance_career',
    'UKPersonalFinance': 'finance_career',
    'starbucks': 'finance_career',

    # EDUCATION / SCIENCE
    'ucla': 'education_science',
    'space': 'education_science',
    'explainlikeimfive': 'education_science',
    'coolguides': 'education_science',
    'WarCollege': 'education_science',
    'languagelearning': 'education_science',

    # LIFESTYLE / HEALTH
    'cars': 'lifestyle_health',
    'Indiemakeupandmore': 'lifestyle_health',
    'femalefashionadvice': 'lifestyle_health',
    'zerocarb': 'lifestyle_health',
    'DesignerReps': 'lifestyle_health',
    'littlespace': 'lifestyle_health',
    'EDC': 'lifestyle_health',
    'EatCheapAndHealthy': 'lifestyle_health',
    'malefashionadvice': 'lifestyle_health',
    'Anticonsumption': 'lifestyle_health',
    'Cooking': 'lifestyle_health',
    'GetMotivated': 'lifestyle_health',

    # CREATIVE / HOBBIES
    'MLPLounge': 'creative_hobbies',
    'WeAreTheMusicMakers': 'creative_hobbies',
    'boardgames': 'creative_hobbies',
    'Cubers': 'creative_hobbies',
    'edmproduction': 'creative_hobbies',
    'whatstheword': 'creative_hobbies',
    'ifyoulikeblank': 'creative_hobbies',
    'conlangs': 'creative_hobbies',
    'funkopop': 'creative_hobbies',
    'chess': 'creative_hobbies',
    'knitting': 'creative_hobbies',
    'audiobooks': 'creative_hobbies',

    # PERSONALITY / IDENTITY
    'furry_irl': 'personality_identity',
    'isfp': 'personality_identity',
    'estp': 'personality_identity',
    'askgaybros': 'personality_identity',
    'mensa': 'personality_identity',
    'lgbt': 'personality_identity',
    'gaybros': 'personality_identity',
    'actuallesbians': 'personality_identity',

    # RELATIONSHIPS
    'socialskills': 'relationships',
    'ForeverAlone': 'relationships',
    'Nicegirls': 'relationships',

    # MENTAL HEALTH
    'collapse': 'mental_health',
    'depressionregimens': 'mental_health',
    'pillhead': 'mental_health',
    'Stims': 'mental_health',

    # SOCIAL DISCUSSION
    'AskEurope': 'social_discussion',
    'AskUK': 'social_discussion',
    'TrueReddit': 'social_discussion',
    'OutOfTheLoop': 'social_discussion',
    'teenagersnew': 'social_discussion',
    'legaladvice': 'social_discussion',
    'TopMindsOfReddit': 'social_discussion',
    'TrollXChromosomes': 'social_discussion',
    'TwoXChromosomes': 'social_discussion',
    'UnethicalLifeProTips': 'social_discussion',
    'CRABsinabucket': 'social_discussion',
    'CrappyAMA': 'social_discussion',

    # NEWS / WORLD
    'UpliftingNews': 'news_world',
    'MapPorn': 'news_world',

    # POLITICS
    'EndFPTP': 'politics',
    'ShitWehraboosSay': 'politics',
    'asktrp': 'politics',
    'Jordan_Peterson_Memes': 'politics',
    'lostgeneration': 'politics',
    'AskFeminists': 'politics',
    'Anarcho_Capitalism': 'politics',
    'TheMotte': 'politics',
    'AskThe_Donald': 'politics',
    'Shitstatistssay': 'politics',
    'TrueCatholicPolitics': 'politics',
    'MHoCCampaigning': 'politics',

    # IDEOLOGY / RELIGION
    'philosophy': 'ideology_religion',

    # GEOGRAPHY / LOCAL
    'newzealand': 'geography_local',
    'Scotland': 'geography_local',
    'CasualUK': 'geography_local',
    'SeattleWA': 'geography_local',
    'UofT': 'geography_local',
    'london': 'geography_local',
    'nyc': 'geography_local',
    'Portland': 'geography_local',
    'singapore': 'geography_local',

    # GENERAL REDDIT
    'UnresolvedMysteries': 'general_reddit',
    'WouldYouRather': 'general_reddit',
    'CircleofTrust': 'general_reddit',
    'MHOL': 'general_reddit',
    'Dreams': 'general_reddit',
    'MovieDetails': 'general_reddit',
    'army': 'general_reddit',
    'guns': 'general_reddit',
    'Parahumans': 'general_reddit',

    # sports
    'Dodgers': 'sports',
    'rugbyunion': 'sports',
    'FCInterMilan': 'sports',
    'olympics': 'sports',
    'washingtonwizards': 'sports',
    'Huskers': 'sports',
    'crossfit': 'sports',
    'footballmanagergames': 'sports',

    # gaming
    'gamegrumps': 'gaming',
    'girlsfrontline': 'gaming',
    'Sekiro': 'gaming',
    'DuelLinks': 'gaming',
    'spikes': 'gaming',
    '2007scape': 'gaming',
    'starcitizen': 'gaming',
    'battlefield_one': 'gaming',
    'TheSilphRoad': 'gaming',
    'PuzzleAndDragons': 'gaming',
    'customhearthstone': 'gaming',
    'splatoon': 'gaming',
    'KingdomHearts': 'gaming',
    'BokuNoHeroAcademia': 'entertainment',
    'Undertale': 'gaming',
    'DragaliaLost': 'gaming',
    'dishonored': 'gaming',
    'thedivision': 'gaming',
    'forhonor': 'gaming',
    'AnthemTheGame': 'gaming',
    'ModernMagic': 'gaming',
    'summonerschool': 'gaming',
    'killingfloor': 'gaming',
    'alitabattleangel': 'entertainment',
    'Kaiserreich': 'gaming',
    'dndmemes': 'gaming',
    'Blackops4': 'gaming',
    'CompetitiveHS': 'gaming',
    'MarvelPuzzleQuest': 'gaming',
    'blackdesertonline': 'gaming',
    'Gamingcirclejerk': 'gaming',
    'FinalFantasy': 'gaming',
    'Diablo': 'gaming',
    'nintendo': 'gaming',
    'MortalKombat': 'gaming',

    # entertainment
    'indieheads': 'entertainment',
    'DDLC': 'gaming',
    'kpop': 'entertainment',
    'NormMacdonald': 'entertainment',
    'thefighterandthekid': 'entertainment',
    'Warhammer40k': 'gaming',
    'HollywoodUndead': 'entertainment',
    'TheOrville': 'entertainment',
    'DunderMifflin': 'entertainment',
    'LetsTalkMusic': 'entertainment',
    'blackmirror': 'entertainment',
    'AnimeFigures': 'entertainment',
    'poppunkers': 'entertainment',
    'TheLastAirbender': 'entertainment',
    'greysanatomy': 'entertainment',
    'horror': 'entertainment',
    'Bastille': 'entertainment',
    'maninthehighcastle': 'entertainment',
    'RedHotChiliPeppers': 'entertainment',
    'MangaCollectors': 'entertainment',
    'comics': 'entertainment',
    'MichaelJackson': 'entertainment',
    'Vaporwave': 'entertainment',
    'GODZILLA': 'entertainment',
    'rickandmorty': 'entertainment',
    'RedLetterMedia': 'entertainment',
    'Muse': 'entertainment',
    'EDM': 'entertainment',

    # memes_humor
    'cursedimages': 'memes_humor',
    'ImGoingToHellForThis': 'memes_humor',
    'therewasanattempt': 'memes_humor',
    'Wellthatsucks': 'memes_humor',
    'quityourbullshit': 'memes_humor',
    'ATBGE': 'memes_humor',
    'PoliticalCompassMemes': 'memes_humor',
    'sadcringe': 'memes_humor',
    'FellowKids': 'memes_humor',
    'instant_regret': 'memes_humor',
    'hmmm': 'memes_humor',
    'iamverybadass': 'memes_humor',
    'cringe': 'memes_humor',
    'beholdthemasterrace': 'memes_humor',

    # personality_identity
    'gay_irl': 'personality_identity',
    'bisexual': 'personality_identity',
    'asexuality': 'personality_identity',
    'LGBTeensGoneMild': 'personality_identity',
    'Braincels': 'personality_identity',
    'traaaaaaannnnnnnnnns': 'personality_identity',
    'shittyMBTI': 'personality_identity',
    'LGBTeens': 'personality_identity',
    'polyamory': 'personality_identity',

    # relationships
    'MensRights': 'relationships',
    'badwomensanatomy': 'relationships',
    'AskRedditAfterDark': 'relationships',
    'NarcissisticAbuse': 'relationships',
    'raisedbynarcissists': 'relationships',
    'DatingAfterThirty': 'relationships',
    'penis': 'relationships',

    # mental health
    'exmuslim': 'mental_health',
    'autism': 'mental_health',
    'stopdrinking': 'mental_health',
    'AvPD': 'mental_health',
    'BPD': 'mental_health',
    'Psychonaut': 'mental_health',

    # politics / ideology
    'MHOCPress': 'politics',
    'brasilivre': 'politics',
    'ShitPoliticsSays': 'politics',
    'CombatFootage': 'politics',
    'Bombing': 'politics',
    'Reformed': 'ideology_religion',
    'Christian': 'ideology_religion',
    'IntellectualDarkWeb': 'ideology_religion',
    'DebateAChristian': 'ideology_religion',
    'exjw': 'ideology_religion',
    'DebateAnAtheist': 'ideology_religion',
    'GCdebatesQT': 'ideology_religion',
    'Liberalist': 'politics',

    # finance_career
    'realestateinvesting': 'finance_career',
    'ethereum': 'finance_career',
    'AusFinance': 'finance_career',
    'Frugal': 'finance_career',
    'BuyItForLife': 'finance_career',
    'AmazonMerch': 'finance_career',
    'Accounting': 'finance_career',
    'poker': 'finance_career',

    # education_science
    'learnmath': 'education_science',
    'aviation': 'education_science',
    'javascript': 'technology',
    'AcademicPsychology': 'education_science',
    'SampleSize': 'education_science',
    'linguistics': 'education_science',

    # technology
    'audible': 'technology',
    'MouseReview': 'technology',
    'gadgets': 'technology',

    # lifestyle_health
    'trees': 'lifestyle_health',
    'food': 'lifestyle_health',
    'muacirclejerk': 'lifestyle_health',
    'Indiemakeupandmore': 'lifestyle_health',
    'fasting': 'lifestyle_health',
    'Bless': 'lifestyle_health',
    'gainit': 'lifestyle_health',
    'travel': 'lifestyle_health',
    'Baking': 'lifestyle_health',

    # creative_hobbies
    'cats': 'creative_hobbies',
    'natureismetal': 'creative_hobbies',
    'Disneyland': 'creative_hobbies',
    'HomeImprovement': 'creative_hobbies',
    'woahdude': 'creative_hobbies',
    'whatisthisthing': 'creative_hobbies',
    'vexillology': 'creative_hobbies',
    'knifeclub': 'creative_hobbies',

    # geography_local
    'britishproblems': 'geography_local',
    'brasilivre': 'geography_local',
    'Romania': 'geography_local',
    'philadelphia': 'geography_local',
    'LosAngeles': 'geography_local',
    'milwaukee': 'geography_local',
    'SaltLakeCity': 'geography_local',
    'nova': 'geography_local',
    'longbeach': 'geography_local',

    # social_discussion
    'forwardsfromgrandma': 'social_discussion',
    'Weibsvolk': 'social_discussion',
    'MaliciousCompliance': 'social_discussion',
    'circlebroke2': 'social_discussion',
    'confessions': 'social_discussion',
    'creepyPMs': 'social_discussion',
    'SeriousConversation': 'social_discussion',
    'bestof': 'social_discussion',
    'self': 'social_discussion',

    # news_world
    'watchpeopledie': 'news_world',
    'NatureIsFuckingLit': 'news_world',

    # general reddit
    'Ice_Poseidon': 'general_reddit',
    'CrappyAMA': 'general_reddit',
    'Retconned': 'general_reddit',
    'RMTK': 'general_reddit'
}